manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: scybin
      url-base: https://github.com/scybin
    - name: mwandzik
      url-base: https://github.com/mwandzik
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-keyboard-chitin
      remote: scybin
      revision: main
    - name: zmk-driver-pim447
      remote: mwandzik
      revision: master
  self:
    path: config
